deploymentMode: SingleBinary
statefulset:
  loki-chunks-cache:
    replicaCount: 1
    resources:
      requests:
        cpu: "50m"
  loki-results-cache:
    replicaCount: 1
    resources:
      requests:
        cpu: "50m"
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  resources:
    requests:
      memory: "100Mi"   # Request 512MB of memory
      cpu: "20m"       # Request 250 millicpu (0.25 CPU)
    limits:
      memory: "100Mi"     # Limit to 1GB of memory
      cpu: "20m" 
  storage:
    type: 'filesystem'
  schemaConfig:
    configs:
      - from: 2024-04-01
        object_store: filesystem
        store: tsdb
        schema: v13
        index:
          prefix: index_
          period: 24h
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0
singleBinary:
  replicas: 1